#Windows.yml
# it is suggested that these be encrypted with ansible-vault:
# ansible-vault edit group_vars/windows.yml
ansible_user: administrator@TEST.INT
ansible_password: Wh1t3fr0g
ansible_port: 5986
ansible_winrm_transport: kerberos
ansible_connection: winrm
# The following is necessary for Python 2.7.9+ (or any older Python that has backported SSLContext, eg, Python 2.7.5 on RHEL7) when us$
ansible_winrm_server_cert_validation: ignore
